Fix config.ts: read settings and not use internal-build-dir by default
anoma/vscode-juvix pull request #132
Opened 2024-07-16 02:38 UTC by jonaprieto

Before this PR and after 0.2.0, the settings window seems to no longer detect the options set for some unknown reason. It's possible that the logic used in the 'VsCodeSettings' file has become outdated due to the latest updates and the use of a very new vscode engine (+1.90.0). Despite my attempts to fix its behavior, I ultimately gave up. This PR now reads options according to the latest API. Additionally, the internal build directory is no longer used by default; it's now optional.

This PR goes on top:

- #131

Note: If the user changes any option in the Settings panel, they need to reload the window or reset the vscode for the changes to take effect.

2024-07-17 08:11 UTC, lukaszcz commented on src/tasks.ts
> +      let cmd = (JuvixExec + ` ${input}`).replace('\n', '').replace('  ', ' ');
Is this a problem?

2024-07-17 08:27 UTC, lukaszcz commented on src/tasks.ts
> +      const buildDir = config.getInternalBuildDir();
It seems like indentation is missing here

2024-07-17 08:27 UTC, lukaszcz commented on src/tasks.ts
>        break;
Again, seems like indentation is wrong

2024-07-17 08:28 UTC, lukaszcz requested changes
Fix indentation issues

2024-07-17 16:28 UTC, jonaprieto commented on src/tasks.ts
> +      let cmd = (JuvixExec + ` ${input}`).replace('\n', '').replace('  ', ' ');
Not, I removed this, I was using this for debugging purposes.

2024-07-17 16:29 UTC, jonaprieto commented on src/tasks.ts
>        break;
Fixed it.

2024-07-17 16:29 UTC, jonaprieto commented on src/tasks.ts
> +      const buildDir = config.getInternalBuildDir();
Fixed it.

2024-07-18 10:01 UTC, lukaszcz commented on src/tasks.ts
> +      let cmd = (JuvixExec + ` ${input}`).replace('\n', '').replace('  ', ' ');
This line is still in the code. So it's fine to replace only a single occurrence of '\n', and this is for debugging only?

2024-07-18 10:01 UTC, lukaszcz approved these changes

2024-07-18 15:56 UTC, merged